### ISSUE TITLE
Is it allow to only compile .proto file under specify folder?

### ISSUE THREAD

**Issue by Guxin233** [5argon/protobuf-unity#3]
When click Force Compilation, all .proto file under Unity project will auto create relatice C# file. Is it allow to only compile .proto file under specify folder? Because some .proto file under Google official protobuf folder also be executed (but I dont hope so...), and some of this proto file use protobuf2 syntax will occurred error.
![1](https://user-images.githubusercontent.com/19237159/40595746-1eb029e8-6269-11e8-913b-70329fba1721.png)
![1](https://user-images.githubusercontent.com/19237159/40595769-4da90e36-6269-11e8-9ed6-07774d11e14b.png)

**Comment by 5argon** [comment]
Oh, that would be the case. In my project I use Protobuf dll from NuGet so they won't get compiled.

Currently the tool will compiles everything inside your project because the use of asset importer. You could hack around it in `CompileProtobufAssetPath` function inside `ProtobufUnityCompiler`. Check the path there and return `false` should exempt that folder.
